### ISSUE TITLE
Alert Correlation

### ISSUE THREAD

**Issue by robxxxx** [dunbarcyber/cyphon#248] opened 2017-10-05 12:40 UTC
Can't I use this for automatic incident correlation?

For example: If I get 10 device failure alert from customer site X within certain time frame, I want Cyphon to generate one alert which include all the incidents from monitoring software. The Cyphon alert should include each email's content (emails sent from the monitoring system).

Thanks!

**Comment by lhadjchikh** [comment] 2017-10-05 14:33
Currently, you can handle this by using a Muzzle (under the "Configuring Alerts" panel) and a Context (under the "Investigating Alerts" panel):

1. Configure the Muzzle to identify duplicates based on the values of certain "matching fields" in the data (for example, "signature_id, source_ip"). Then, instead of generating duplicate alerts, the number of "incidents" on the first alert will increment for each suppressed duplicate alert.

2. Configure a Context to identify the duplicate alert data:

   - Name the Context "related alerts" (or whatever you'd like).
   - Set both the "primary distillery" and the "related distillery" to the Distillery where the data is being saved.
   - Set the "before time interval" to 0 and the "after time interval" to match the time interval on the Muzzle from step 1.
   - Set the "filter logic" to "AND".
   - Add "context filters" to match the criteria for the Muzzle in step 1. For example, if the "matching fields" were "signature_id, source_ip", you'd have two ContextFilters: one in which "signature_id equals signature_id" and the other in which "source_ip equals source_ip".

Now, when you get an alert that's associated with multiple incidents, you can open the "Analyze" pane in the Cyclops UI, then click on the "Related Data" panel and select the Context you created in step 2. This should return results for the duplicate data. If the number of results returned is less than the number of incidents on the original alert, adjust the Context time interval slightly to be sure you're capturing everything. (Muzzles time intervals are based on the time at which Cyphon alerts are generated, whereas Contexts are based on the time field in the data itself, so these time intervals can be slightly different.)

Here are some relevant docs that may help:
http://cyphon.readthedocs.io/en/latest/user-manual/configuring-alarms.html#watchdogs
http://cyphon.readthedocs.io/en/latest/user-manual/investigating-alerts.html

Let me know if this solution works for you for now. We might consider an easier way to retrieve duplicate incidents in the future...

**Comment by robxxxx** [comment] 2017-10-08 21:31
Hi lhadjchikh

Sorry for the delayed response. Thanks a lot! You explanation helped me a lot.
Though it needs few adjustment according to my needs, I saw the possibility do it with your explanation. 

Once more alerts get populated with this logic, I will let you some other things I'm concerned.

Thanks again

**Comment by robxxxx** [comment] 2017-10-08 22:28
Hi lhadjchikh

I want to match <b>Customer: </b><br /> filed in the email constant to identify associated alerts. 

Would that be possible?

**Comment by lhadjchikh** [comment] 2017-10-09 13:41
Yes, this should be possible. You just have to configure a few things:

1. Create a BottleField called "customer" and add it to the Bottle you're using for storing emails.

**Comment by robxxxx** [comment] 2017-10-10 06:28
Hi lhadjchikh,

Thank you for your detailed demonstration. However, context feature does not seem to work, because it does not show me the related incidents, when I try to make a data correlation with the same customer field. I wounder if there is any caveats for this feature.  

Additionally, I found that "Test this parser" does not work as intended, though I have been able to do it with Regex101 website.

Thank you!

**Comment by lhadjchikh** [comment] 2017-10-10 13:16
The "Test this parser" tool for MailParsers needs the raw source of an email so that it can create an email object from the string. I used this as a test string for the regex `Customer:\s(.*?)\W`:
```
Date: Oct, 10 Apr 2017 12:00:00 +0000 (UTC)
From: sender@email.com
To: "recipient@email.com" <recipient@email.com>
Subject: test string
MIME-Version: 1.0
Content-Type: multipart/mixed;
    boundary="----=_Part_18598_984397735.1460975954577"
X-Original-Sender: no_reply@example.com
------=_Part_18598_984397735.1460975954577
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

Customer: Acme

------=_Part_18598_984397735.1460975954577
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
<html>
  <head></head>
  <body>
    <div>Customer: Acme</div>
  </body>
</html>
------=_Part_18598_984397735.1460975954577--
```
I still need to add that to the documentation...

With regard to Contexts, can you double check the following?:

- the "customer" field is being added and populated as expected in processed email data
- the Taste on the Container admin page has the date defined:
![taste](https://user-images.githubusercontent.com/5034226/31387763-8f13b9d2-ad99-11e7-9b11-5f1075fb14d7.png)
- there are emails with date values that fall within the time frame specified by the Context

When a Context doesn't return expected results, I often loosen the criteria on the Context by expanding the time frame to a long period (say, 30 days), or by removing any ContextFilters. This helps me determine whether the problem is with the date field or with the fields used in the ContextFilters.

**Comment by lhadjchikh** [comment] 2017-11-27 14:58
Closing this out, but feel free to reopen if it's still an issue.

**Comment by robxxxx** [comment] 2018-01-22 12:09
I'm sorry for the delayed response, but context feature did not work for me. I have tried all of the thing you mentioned above.

**Comment by lhadjchikh** [comment] 2018-01-22 15:36
Sorry about that. I would look at the data in Kibana and confirm the following:

- the names of the fields you are trying to match are represented correctly in the Containers you created for them in Cyphon (you can tell this by looking at the container preview on the Container admin page)

- the name of the Collection in Cyphon matches the value of the '_type' field of the document in Kibana

- the name of the Warehouse matches the value of the '_index' field (minus the part with the datestamp, if it's a time series index)

- confirm that the date field chosen for the Container's Taste matches the date field shown in Kibana

[Cyphon 1.6](https://www.cyphon.io/blog/2018/1/18/cyphon-release-1-6) contains a new search tool, so you might also try using that to see if Cyphon is able to search your data as expected.

**Comment by lhadjchikh** [comment] 2018-03-22 17:07
Closing this again due to inactivity, but feel free to reopen it if you're still having problems.

**Closed by lhadjchikh** 2018-03-22 17:07 UTC
