### ISSUE TITLE
Domain Cert - cyphon/docker?

### ISSUE THREAD

**Issue by uxlab9** [dunbarcyber/cyphon#120] opened 2017-06-30 17:44 UTC
Installing Cyphon onto a desktop inside of enterprise domain. I have followed all the directions listed at Cyphon.io but when I get to Development Environment:
$ cd /opt/cyphon/cyphondock
$ sudo docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

I am prompted for [sudo] password for UserName: After typing in my correct password. The return function is:
"Pulling postgres (mdillon/postgis:9.6)...
ERROR: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority"

I have copied and put my Domain Cert in /home/documents folder and even copied it to the /home/certs folder. I then ran:
$ sudo cp /home/UserName/certs/xx-xx-xx.crt /usr/share/ca-certificates/extra/xx-xx-xx.crt to install my domain cert.

But I am still getting: ERROR: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority.

How does docker view certs, how do I resolve. At a stand still. Thanks

Running Ubuntu 16.04

**Comment by lhadjchikh** [comment] 2017-06-30 17:57
I haven't encountered this issue before, so I'm not sure, unfortunately. I would try to get support from Docker. This issue seems similar: https://github.com/docker/toolbox/issues/603

**Comment by uxlab9** [comment] 2017-06-30 18:01
Thanks, I submitted a request with them for this issue.

**Comment by uxlab9** [comment] 2017-07-05 13:08
I submitted a request with Docker. What possible suggestions do you think would be the issue ERROR: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority. And the certificate is signed

**Comment by lhadjchikh** [comment] 2017-07-05 13:18
Have you tried the remedies suggested in https://github.com/docker/toolbox/issues/603?

**Comment by uxlab9** [comment] 2017-07-05 14:08
I started Ubuntu terminal and ran cd /opt/cyphon/cyphondock and then docker-machine ls as stated docker/toolbox#603 and I get a: command not found. I looked over the forum #603 post and unless I am mistaken it appears that my proxy running on Ubuntu is not running.

**Comment by chasepbrewer** [comment] 2017-07-05 14:57
You're getting the "command not found" error because you don't have docker-machine installed on your system, but you don't need docker-machine to troubleshoot this issue. That link was just a reference to the problem you're most likely having. It's the best we can do because this is a docker and/or network issue and not something caused by the application.

There may not be a proxy installed on your machine, but if your company has a firewall or any sort of endpoint protection they may have rules in place that drop certain certifications from downloading. Our company has that on our internal network to prevent people from accidentally downloading potentially hazardous certs. The first thing I said when I saw your issue was "It sounds like a machine on his network somewhere dropped the cert before it got to his machine".

**Comment by uxlab9** [comment] 2017-07-05 15:06
Yes we have some sort of endpoint encryption running. What rule would I ask to have set to make sure the cert stays in place everyday while I am running the program?

**Comment by chasepbrewer** [comment] 2017-07-05 15:20
That's something your system administrator has to take care of. You'll have to have a talk with them to see what's being dropped in the network when your downloading Cyphon's dependencies.

I'm closing this issue because this problem is outside the scope of our application. This is an internal company networking issue having to do with tools that we don't manage. I'm sorry but there's nothing we can do on our side to fix it.

**Closed by chasepbrewer** 2017-07-05 15:20 UTC
