### ISSUE TITLE
Muzzing not working on closed alerts

### ISSUE THREAD

**Issue by robinlennox** [dunbarcyber/cyphon#223] opened 2017-09-15 03:56 UTC
I've found an issue where if an alerts is muzzled and the muzzled alerts is closed, Cyphon will create a new alerts even though it's a duplicate if the alerts occurs again. I would expect the behaviour of the muzzle to reopen the old alerts as the alerts is still related to the closed alerts.

Maybe add an option to suppress specific alerts in the Cyphon interface.

**Comment by darvid** [comment] 2017-09-15 12:39
Hmm, I don't think that the alert muzzling checks the alert status at all to determine what alerts to muzzle. What's the interval set on your muzzles? Perhaps it's too low and the new alert occurred slightly outside of its window?

**Comment by robinlennox** [comment] 2017-09-17 19:31
Hi, the interval was set to 30 days.

**Comment by lhadjchikh** [comment] 2017-09-18 13:13
Thanks for reporting this! I think it's probably caused by an IntegrityError relating to the muzzle hash. I'll work on a fix!

Some things to be aware of: 

- The level of the Alert is determined by the Watchdog, not by the level of previous Alerts. Taking into account manual changes a user has made to the levels of previous Alerts would require machine learning, which we hope to incorporate in the future. :-)

- In addition to time frame and Alert level, Muzzles also take into account some other features of Alerts, described here: http://cyphon.readthedocs.io/en/latest/architecture/generating-alerts.html#muzzles

**Comment by robinlennox** [comment] 2017-09-18 20:25
Could you create a hash of the message and check if that already exists to prevent duplicates?

**Comment by lhadjchikh** [comment] 2017-09-18 20:35
Yes, I'm testing this fix now in https://github.com/dunbarcyber/cyphon/pull/229. If it finds that an edited Alert will create a duplicate `muzzle_hash`, it uses the current time to reset the starting time of the muzzle interval (instead of using the `created_date`). You'll probably want to refine the Watchdog so it sets Alert levels more accurately, though. Otherwise, it will keep generating new Alerts under the wrong level after you manually change the level of older Alerts.

**Comment by lhadjchikh** [comment] 2017-09-18 20:51
Hmm, thinking about it more, using the current time may not be sufficient to always prevent duplicates. I will revisit this tomorrow. :-)

**Comment by lhadjchikh** [comment] 2017-09-19 19:28
Fixed in https://github.com/dunbarcyber/cyphon/pull/229, which will be part of the 1.5 release.

**Closed by lhadjchikh** 2017-09-19 19:28 UTC
Labels: bug
