### ISSUE TITLE
integrate with any opensource Issue

### ISSUE THREAD

**Issue by engmahmoud** [dunbarcyber/cyphon#401] opened 2018-02-16 05:19 UTC
can i integrate cyphon with any opensource Issue system like osticket or openproject alternative to jira????

**Comment by lhadjchikh** [comment] 2018-02-16 14:31
Hi @engmahmoud. Integrating with osTicket would just require developing another package similar to the `platforms.jira` package, which creates a subclass of `responder.carrier.Carrier` to interact with the REST API. If you have any Python programming experience, feel free to try it yourself and create a PR. Otherwise, I'll see what I can do. This is the second request we've gotten for osTicket integration, so it'd be great to have.

I'm going to close this out as a duplicate of https://github.com/dunbarcyber/cyphon/issues/336, but feel free to comment more or chat about it on [Gitter](https://gitter.im/cyphonproject/Lobby).

**Closed by lhadjchikh** 2018-02-16 14:31 UTC
Labels: duplicate
